In [1]:
import numpy as np

In [2]:
# ADDING TWO MATRICES
a = np.array([[1,2,3],
                            [4,5,6],
                            [7,8,9]])

b = np.array([[11,12,13],
                            [14,15,16],
                            [17,18,19]])

a + b

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [3]:
a * 2   # multiplying a matrix by a scalar

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
# creating an identity matrix of n x n dimensions
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
# array redimensioning
x = np.array([i for i in range(27)])
x.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
# array datatype conversion
# can also be used to obtain boolean from binary arrays
bool_x = np.array([[True, True, True],
                                      [False, True, False],
                                      [True, False, True]])

bool_x.astype(int)

array([[1, 1, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [7]:
# horizontal stacking of arrays
g = np.array([[1,2,3],[4,5,6]])
h = np.array([[6,7,8],[9,10,11]])

np.hstack((g,h))

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

In [8]:
# vertical stacking of arrays
f = np.array([[21,23,24],[26,27,28]])
d = np.array([[31,32,33],[34,35,36]])

np.vstack((f,d))

array([[21, 23, 24],
       [26, 27, 28],
       [31, 32, 33],
       [34, 35, 36]])

In [9]:
# custom sequence generation
np.arange(0,101,2)   # start, stop, step

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [10]:
# Getting the positions (indexes) where elements of 2 numpy arrays match
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,3,2,4,5])
np.where(arr1 == arr2)

(array([0, 3, 4], dtype=int64),)

In [11]:
# Generation of given count of equally spaced numbers within a specified range
np.linspace(0,9,5)

array([0.  , 2.25, 4.5 , 6.75, 9.  ])

In [12]:
# Matrix Generation containing one particular value
np.full((2,3), 5) 

array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
# Array Generation by repeatition of a small array across each dimension
z = np.array([[1,2,3],[4,5,6]])
np.tile(z,10)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
        2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4,
        5, 6, 4, 5, 6, 4, 5, 6]])

In [14]:
# Array Generation of random integers within a specified range
np.random.seed(10)
np.random.randint(0,10, size = (5,5))

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8],
       [4, 1, 3, 6, 5]])

In [15]:
# Array Generation of random numbers following normal distribution
np.random.seed(123)
np.random.normal(size=(5,5))

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025],
       [ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ],
       [-0.67888615, -0.09470897,  1.49138963, -0.638902  , -0.44398196],
       [-0.43435128,  2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904, -1.25388067]])

In [16]:
#  Matrix Multiplication
a = np.array([[1,2,3],
                          [4,5,6],
                          [7,8,9]])

b = np.array([[2,3,4],
                          [5,6,7],
                          [8,9,10]])

np.matmul(a, b)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [17]:
# transposing of an array
tre = np.array([[1,2,3],[4,5,6],[7,8,9]])
tre.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
# Sine of an Angle (in radians)
angles = np.array([3.14, 3.14/2, 6.28])
np.sin(angles)

array([ 0.00159265,  0.99999968, -0.0031853 ])

In [19]:
# Generating the array element indexes such that the array elements appear in ascending order
array = np.array([10,1,5,2])
np.argsort(array)

array([1, 3, 2, 0], dtype=int64)